### ISSUE TITLE
Errors and warnings in syslog

### ISSUE THREAD

**Issue by Dids** [SimonFair/unraid.iSCSI#3]
Took a while, but I got this absolutely _fantastic_ plugin working, however I noticed that occasionally it shows `error: /Settings/iSCSISettings: wrong csrf_token` in the syslog. I believe this happens when making changes, as I end up with a white screen and have to reload the page.

Additionally, at least when connecting from a Windows client, the following message/warning gets repeated over and over again in syslog:
```
iSCSI/iqn.1991-05.com.microsoft:didspc: Unsupported SCSI Opcode 0x85, sending CHECK_CONDITION.
target_cmd_parse_cdb: 9 callbacks suppressed
```

These aren't blocking issues by any means, but figured they were still worth reporting.

Also slightly off topic, but are there plans to allow default/any initiator names, without having to configure them every time? Granted this can become a security issue, but the iSCSI servers I've dealt with before have allowed any initiator name.

**Comment by SimonFair** [comment]
Thanks for reporting will look into the issues.

Re syslog i believe at present there is no way to suppress those log entries and also they dont cause any issues

Any specific page for errors?

**Comment by ich777** [comment]
@Dids from what I know this is only a opcode for reading the smart data (not only smart) from a disk and since your other issue here talks about a FileIO volume it simply can't read the smart data because there is no smart data from a image file available.
This message should not harm your system or effect performance in any way.

**Comment by ich777** [comment]
@Dids can we close this issue or better speaking is your question answered?

**Comment by Dids** [comment]
@ich777 This can be closed, thank you.
